stages:
  - init
  - test
  - build
  - deploy

init:
  stage: init
  script:
    - export
    - echo 'hello runner~'

test:
  stage: test
  script:
    - mvn -B -e test

build:
  stage: build
  script:
    - mvn -B -e install -Dmaven.test.skip=true

deploy:
  stage: deploy
  script:
    - echo 'no space to deploy now :('
